export const CATEGORY_LABELS: Record<string, string> = {
  'healthcare': 'Healthcare',
  'technology': 'Technology',
  'finance': 'Finance',
  'education': 'Education',
  'retail': 'Retail',
  'manufacturing': 'Manufacturing',
  'real_estate': 'Real Estate',
  'hospitality': 'Hospitality',
  'transportation': 'Transportation',
  'energy': 'Energy',
  'telecommunications': 'Telecommunications',
  'government': 'Government',
  'non_profit': 'Non-Profit',
  'professional_services': 'Professional Services',
  'agriculture': 'Agriculture',
  'entertainment': 'Entertainment',
  'construction': 'Construction',
  'pharmaceuticals': 'Pharmaceuticals',
  'automotive': 'Automotive',
  'food_beverage': 'Food & Beverage',
  'insurance': 'Insurance',
  'legal': 'Legal',
  'media': 'Media',
  'utilities': 'Utilities',
  'other': 'Other'
};